# Generated by Django 2.0.4 on 2018-05-09 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
    ]
